#!/usr/bin/env python3
"""Generate Dockerfiles for the Esempe temurin runner images.

For every version directory under temurin/ (e.g. temurin/25), an optional
plain-text file named package.extras lists additional APT packages to install
(one package name per line, '#' starts a comment). This script renders a
Dockerfile based on:

    eclipse-temurin:<version>-jre-resolute        (Ubuntu 26.04 / Resolute)

installing a fixed set of standard runner packages plus the extras from
package.extras. The built image is meant to be tagged as:

    ghcr.io/esempe-id/eclipse-temurin:<version>-jre

Usage examples:

    python3 scripts/generate_dockerfiles.py                 # all versions
    python3 scripts/generate_dockerfiles.py --version 21    # one version
    python3 scripts/generate_dockerfiles.py --print-tags    # also print tags
    python3 scripts/generate_dockerfiles.py --check         # CI drift check
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
TEMURIN_DIR = REPO_ROOT / "temurin"
EXTRAS_FILE = "package.extras"
DOCKERFILE = "Dockerfile"

BASE_IMAGE = "eclipse-temurin"
BASE_VARIANT = "jre-resolute"

IMAGE_REGISTRY = "ghcr.io/esempe-id/eclipse-temurin"
IMAGE_VARIANT = "jre"

IMAGE_SOURCE_URL = "https://github.com/esempe-id/seed"

# Packages that are always installed, regardless of package.extras.
STANDARD_PACKAGES = [
    "curl",
    "jq",
    "unzip",
    "wget",
    "bash",
    "ca-certificates",
]

VERSION_RE = re.compile(r"^\d+$")

_EXTRAS_TEMPLATE = """\
# Extra APT packages to install on top of eclipse-temurin:<version>-jre-resolute.
# One package per line. Blank lines and lines starting with '#' are ignored.
# Example:
#   git
#   git-lfs
#   tini
#
# Regenerate the Dockerfile afterwards with:
#   python3 scripts/generate_dockerfiles.py
"""


def discover_versions() -> list[Path]:
    """Return the temurin version directories, sorted by name."""
    if not TEMURIN_DIR.is_dir():
        return []
    return sorted(
        entry
        for entry in TEMURIN_DIR.iterdir()
        if entry.is_dir() and VERSION_RE.match(entry.name)
    )


def load_extra_packages(version_dir: Path) -> list[str]:
    """Read the package.extras file from a version directory.

    Lines are trimmed; blank lines and lines starting with '#' are ignored.
    An inline comment may follow a package name (everything after '#').
    Missing files simply yield no extra packages.
    """
    extras_file = version_dir / EXTRAS_FILE
    if not extras_file.is_file():
        return []
    packages: list[str] = []
    for raw_line in extras_file.read_text(encoding="utf-8").splitlines():
        line = raw_line.split("#", 1)[0].strip()
        if not line:
            continue
        packages.append(line.split()[0])
    return packages


def dedupe(items: list[str]) -> list[str]:
    """Return items with duplicates removed, preserving first occurrence order."""
    seen: set[str] = set()
    result: list[str] = []
    for item in items:
        if item not in seen:
            seen.add(item)
            result.append(item)
    return result


def render_dockerfile(version: str, extra_packages: list[str]) -> str:
    """Render the Dockerfile content for a given temurin version."""
    base_image = f"{BASE_IMAGE}:{version}-{BASE_VARIANT}"
    image_ref = f"{IMAGE_REGISTRY}:{version}-{IMAGE_VARIANT}"

    # Extras that actually add something beyond the standard package set.
    extra_resolved = dedupe(pkg for pkg in extra_packages if pkg not in STANDARD_PACKAGES)
    extra_resolved.sort()
    packages = dedupe(STANDARD_PACKAGES + extra_resolved)
    packages.sort()

    extras_summary = ", ".join(extra_resolved) if extra_resolved else "(none)"

    lines = [
        "# AUTO-GENERATED by scripts/generate_dockerfiles.py - DO NOT EDIT BY HAND.",
        "# Regenerate with: python3 scripts/generate_dockerfiles.py",
        "#",
        f"# Base image:      {base_image}",
        f"# Output image:    {image_ref}",
        f"# Extra packages:  {extras_summary}",
        "",
        f"FROM {base_image}",
        "",
        f'LABEL org.opencontainers.image.source="{IMAGE_SOURCE_URL}"',
        f'LABEL org.opencontainers.image.title="Esempe runner image (Temurin {version} JRE)"',
        f'LABEL org.opencontainers.image.description="Temurin {version} JRE with runner system packages"',
        f'LABEL org.opencontainers.image.version="{version}-{IMAGE_VARIANT}"',
        f'LABEL org.opencontainers.image.ref.name="{image_ref}"',
        "",
        "# Install packages as root (the temurin base image already runs as root).",
        "USER root",
        "",
        "# Install the standard runner packages plus the extras from package.extras.",
        "RUN apt-get update \\",
        "    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \\",
    ]
    for package in packages:
        lines.append(f"        {package} \\")
    lines.append("    && rm -rf /var/lib/apt/lists/*")
    lines.append("")
    lines.extend([
        "# Configure user container with home directory /home/container (UID 1000).",
        "# If ubuntu user already exists (default on Ubuntu 24.04+ base images), rename it.",
        "RUN if id -u ubuntu >/dev/null 2>&1; then \\",
        "        usermod -d /home/container -l container ubuntu \\",
        "        && (groupmod -n container ubuntu || true); \\",
        "    elif ! id -u container >/dev/null 2>&1; then \\",
        "        (groupadd -g 1000 container || true) \\",
        "        && (useradd -d /home/container -m -u 1000 -g 1000 -s /bin/bash container || useradd -d /home/container -m -u 1000 -s /bin/bash container); \\",
        "    fi \\",
        "    && mkdir -p /home/container \\",
        "    && chown -R 1000:1000 /home/container",
        "",
        "USER container",
        "ENV USER=container HOME=/home/container",
        "WORKDIR /home/container",
        "",
    ])

    return "\n".join(lines) + "\n"


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate Dockerfiles for the temurin/ runner images.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "--version",
        action="append",
        default=[],
        metavar="N",
        help="Only process the given temurin version(s); repeatable. "
        "Defaults to all version directories under temurin/.",
    )
    parser.add_argument(
        "--init-extras",
        action="store_true",
        help="Create a package.extras template (header comment only) in a "
        "version directory that does not have one yet.",
    )
    parser.add_argument(
        "--print-tags",
        action="store_true",
        help="Print ghcr.io/esempe-id/eclipse-temurin:N-jre for each processed "
        "version, one per line (useful for CI).",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Do not write files; verify every generated Dockerfile is up to "
        "date. Exits with code 1 when any Dockerfile is stale or missing.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)

    all_versions = discover_versions()
    if not all_versions:
        print(f"error: no version directories found under {TEMURIN_DIR}", file=sys.stderr)
        return 1

    if args.version:
        requested = set(args.version)
        available = {entry.name for entry in all_versions}
        missing = sorted(requested - available)
        if missing:
            print(
                f"error: unknown temurin version(s): {', '.join(missing)} "
                f"(available: {', '.join(sorted(available))})",
                file=sys.stderr,
            )
            return 1
        version_dirs = [entry for entry in all_versions if entry.name in requested]
    else:
        version_dirs = all_versions

    stale = False
    for version_dir in version_dirs:
        version = version_dir.name
        extras_file = version_dir / EXTRAS_FILE

        if args.init_extras and not extras_file.is_file():
            extras_file.write_text(_EXTRAS_TEMPLATE, encoding="utf-8")
            print(f"created {extras_file}")
        if not extras_file.is_file():
            print(
                f"[warn] {extras_file} does not exist; using no extra packages "
                f"(run with --init-extras to create a template)",
                file=sys.stderr,
            )

        extra_packages = load_extra_packages(version_dir)
        content = render_dockerfile(version, extra_packages)
        target = version_dir / DOCKERFILE

        if args.check:
            if not target.is_file() or target.read_text(encoding="utf-8") != content:
                print(f"[check] {target} is out of date", file=sys.stderr)
                stale = True
        else:
            target.write_text(content, encoding="utf-8")
            print(f"generated {target}")

        if args.print_tags:
            print(f"{IMAGE_REGISTRY}:{version}-{IMAGE_VARIANT}")

    return 1 if stale else 0


if __name__ == "__main__":
    sys.exit(main())
